<a href="https://colab.research.google.com/github/roquearmas/pruebasIA/blob/main/Q_Learning_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
Q=np.zeros((21,4),dtype=int)

R=np.zeros((22,4),dtype=int)
v1=0.2 # Factor de aprendizaje learning rate
y1=0.8 # Factor de descuento discount factor

v2=0.8 # Factor de aprendizaje learning rate
y2=0.2 # Factor de descuento discount factor


for i in (range(21)):
  for j in (range(4)):
    if 20-i-j>=1:
      Q[i,j]=20-i-j
    else:
      Q[i,j]=-1

#Q=np.vstack([Q,[-1,-1,-1,-1]])
R[20,0]=100
R[19,1]=100
R[18,2]=100
R[17,3]=100

R[19,0]=95
R[18,1]=95
R[17,2]=95
R[16,3]=95


R[18,1]=90
R[17,2]=90
R[16,3]=90
R[15,1]=90

R[17,2]=85
R[16,3]=85
R[15,1]=85
R[14,2]=85

# R[16,0]=50
# R[15,1]=50
# R[14,2]=50
# R[13,3]=50

# R[11,0]=30
# R[10,1]=30
# R[9,2]=30
# R[8,3]=30

# R[6,0]=25
# R[5,1]=25
# R[4,2]=25
# R[3,3]=25

#R[1,0]=5


print (Q)

R


[[20 19 18 17]
 [19 18 17 16]
 [18 17 16 15]
 [17 16 15 14]
 [16 15 14 13]
 [15 14 13 12]
 [14 13 12 11]
 [13 12 11 10]
 [12 11 10  9]
 [11 10  9  8]
 [10  9  8  7]
 [ 9  8  7  6]
 [ 8  7  6  5]
 [ 7  6  5  4]
 [ 6  5  4  3]
 [ 5  4  3  2]
 [ 4  3  2  1]
 [ 3  2  1 -1]
 [ 2  1 -1 -1]
 [ 1 -1 -1 -1]
 [-1 -1 -1 -1]]


array([[  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,   0,   0],
       [  0,   0,  85,   0],
       [  0,  85,   0,   0],
       [  0,   0,   0,  85],
       [  0,   0,  85, 100],
       [  0,  90, 100,   0],
       [ 95, 100,   0,   0],
       [100,   0,   0,   0],
       [  0,   0,   0,   0]])

In [ ]:
#Seleccionamos un estado al azar
s=1 #Partimos del estado inicial
entrenar=0
T=Q.astype(int)
while(entrenar<100000):
 a=np.random.randint(4) # Acción aleatoria al azar número entero en [0,4]
 while T[s,a]==-1:
    a=np.random.randint(4)

 # T[s,a] es una transición posible
 siguiente=T[s,a] # Estado siguiente
 Q[s,a]=(1-v)*Q[s,a]+v*(R[s,a]+y*max(Q[siguiente,]))
 # print (s,"-->",siguiente)
 if siguiente!=21:
  s=siguiente # Estado siguiente
 else:
  s=0
 entrenar+=1

In [ ]:
#Seleccionamos un estado al azar
s=1 #Partimos del estado inicial
entrenar=0
T=Q.astype(int)
#Seleccionamos un estado al azar
entrenar=0
while(entrenar<100000):
 s=np.random.randint(1,19) # estado aleatorio [0,20]
 a=np.random.randint(4)  # Acción aleatoria al azar número entero en [0,3]
 while T[s,a]==-1:
    a=np.random.randint(4)
    s=np.random.randint(1,19)
 # T[s,a] es una transición posible
 siguiente=T[s,a] # Estado siguiente
 Q[s,a]=(1-v)*Q[s,a]+v*(R[s,a]+y*max(Q[siguiente,]))

 entrenar+=1


In [ ]:
#Seleccionamos un estado al azar
T=Q.astype(int)

entrenar=0
s=0
Q1W=0
Q2W=0
Q1=np.zeros((21,4),dtype=int)
Q2=np.zeros((21,4),dtype=int)
while(entrenar<100000):

 a=np.random.randint(4)  # Acción aleatoria al azar número entero en [0,3]
 while T[s,a]==-1:
    a=np.random.randint(4)

 # T[s,a] es una transición posible
 siguiente=T[s,a] # Estado siguiente
 if siguiente ==-1:
   nula+=1
   s=0
 if (entrenar % 2)==0:
    Q1[s,a]=(1-v1)*Q1[s,a]+v1*(R[s,a]+y1*max(Q1[siguiente,]))
    if T[s,a]==1:
      #print('gana Q1')
      Q1W+=1
      s=0
 else:
    Q2[s,a]=(1-v2)*Q2[s,a]+v2*(R[s,a]+y2*max(Q2[siguiente,]))
    if T[s,a]==1:
      #print('gana Q2')
      Q2W+=1
      s=0

 s=siguiente
 entrenar+=1


In [ ]:
#Seleccionamos un estado al azar

T=Q.astype(int)
entrenar=0
s=0
Q1W=0
Q2W=0
Q1=np.zeros((22,4),dtype=float)
Q2=np.zeros((22,4),dtype=float)
turno=0
nula =0
partida=1
while(entrenar<100000):

 a=np.random.randint(4)  # Acción aleatoria al azar número entero en [0,3]
 while T[s,a]==-1:
    a=np.random.randint(4)
 # T[s,a] es una transición posible
 siguiente=T[s,a] # Estado siguiente
 if siguiente ==-1:
   nula+=1
   s=0
 if (turno % 2)==0:
    Q1[s,a]=(1-v1)*Q1[s,a]+v1*(R[s,a]+y1*max(Q1[siguiente,]))
    if T[s,a]==1:
      #print('gana Q1')
      Q1W+=1
      s=0
      turno =0
      partida+=1
 else:
    Q2[s,a]=(1-v2)*Q2[s,a]+v2*(R[s,a]+y2*max(Q2[siguiente,]))
    if T[s,a]==1:
      #print('gana Q2')
      Q2W+=1
      s=0
      turno =0
      partida+=1
 s=siguiente
 entrenar+=1
 turno+=1

In [ ]:
print('Partidas Jugadas   :',partida)
print('Victorias Jugador 1:',Q1W)
print('Victorias Jugador 2:',Q2W)
print('Partidas nulas     :',nula)
print (Q1)


Partidas Jugadas   : 5540
Victorias Jugador 1: 5189
Victorias Jugador 2: 350
Partidas nulas     : 0
[[  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]
 [211.09898584 207.09941838 203.09935657 203.1001292 ]
 [207.099439   203.10072321 203.10061552 197.98160876]
 [203.1014184  203.10080454 197.98244936 197.98272635]
 [203.10073341 197.98298928 197.98247581 129.98292752]
 [197.98280246 197.98268497 129.98289346 126.70838516]
 [197.98328292 129.98321968 126.70791337 126.70836363]
 [129.98342496 126.70834654 126.70833265 101.36635623]
 [126.70836163 126.70828961 101.36637558 101.36620002]
 [126.70825782 101.36638799 101.36640006 103.98592146]
 [101.36635647 101.36640068 103.98573621 158.38607651]
 [101.36641993 103.98581637 158.38570899 158.38582505]
 [103.98567043 158.38610176 158.3856786  162.47995112]
 [158.38605748 158.3858348  247.4792471  162.48060283]
 [158.38586758 247.479991   162.48066303 165.67917617]
 [162.48013441 162.4

In [ ]:
for t in range(0,21):
   print ("Jugador 1 EStado",t," accion:",1+np.argmax(Q1[t,]))
   print(R[t,])
   print(Q1[t,])
   print(T[t,])
  # print ("Jugador 2 EStado",t," accion:",1+np.argmax(Q2[t,]))


Jugador 1 EStado 0  accion: 1
[0 0 0 0]
[0 0 0 0]
[21 20 19 18]
Jugador 1 EStado 1  accion: 1
[0 0 0 0]
[0 0 0 0]
[20 19 18 17]
Jugador 1 EStado 2  accion: 1
[0 0 0 0]
[72 72 72 38]
[19 18 17 16]
Jugador 1 EStado 3  accion: 1
[0 0 0 0]
[72 72 38 38]
[18 17 16 15]
Jugador 1 EStado 4  accion: 1
[0 0 0 0]
[72 38 38 38]
[17 16 15 14]
Jugador 1 EStado 5  accion: 1
[0 0 0 0]
[38 38 38 16]
[16 15 14 13]
Jugador 1 EStado 6  accion: 1
[0 0 0 0]
[38 38 16 16]
[15 14 13 12]
Jugador 1 EStado 7  accion: 1
[0 0 0 0]
[38 16 16 16]
[14 13 12 11]
Jugador 1 EStado 8  accion: 1
[0 0 0 0]
[16 16 16  8]
[13 12 11 10]
Jugador 1 EStado 9  accion: 1
[0 0 0 0]
[16 16  8  8]
[12 11 10  9]
Jugador 1 EStado 10  accion: 1
[0 0 0 0]
[16  8  8  8]
[11 10  9  8]
Jugador 1 EStado 11  accion: 4
[0 0 0 0]
[ 8  8  8 26]
[10  9  8  7]
Jugador 1 EStado 12  accion: 3
[0 0 0 0]
[ 8  8 26 26]
[9 8 7 6]
Jugador 1 EStado 13  accion: 2
[0 0 0 0]
[ 8 26 26 26]
[8 7 6 5]
Jugador 1 EStado 14  accion: 4
[0 0 0 0]
[26 26 26 53]
[7 6 